//Page
export const SET_SCROLL_POSITION_Y = 'SET_SCROLL_POSITION_Y';
export const SET_VIEWPORT_HEIGHT = 'SET_VIEWPORT_HEIGHT';
export const SET_VIEWPORT_WIDTH = 'SET_VIEWPORT_WIDTH';
export const SET_PAGE_HEIGHT = 'SET_PAGE_HEIGHT';
export const SET_PAGE_WIDTH = 'SET_PAGE_WIDTH';

//MobileMenu
export const SET_MOBILE_MENU_OPENED = 'SET_MENU_VISIBLE';
export const TOGGLE_MOBILE_MENU_OPENED = 'TOGGLE_MENU';
